-- 分区表创建脚本
-- 用途：创建三个分区表结构
-- 执行时间：迁移阶段1
-- 注意：执行前请备份数据库

-- ============================================
-- 1. 创建 region_customer_statistics 分区表
-- ============================================
CREATE TABLE IF NOT EXISTS region_customer_statistics (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    YEAR INT NOT NULL COMMENT '年份',
    MONTH INT NOT NULL COMMENT '月份',
    WEEK_SEQ INT NOT NULL COMMENT '周序号',
    REGION VARCHAR(255) NOT NULL COMMENT '区域名称',
    D30 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D30档位客户数',
    D29 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D29档位客户数',
    D28 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D28档位客户数',
    D27 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D27档位客户数',
    D26 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D26档位客户数',
    D25 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D25档位客户数',
    D24 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D24档位客户数',
    D23 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D23档位客户数',
    D22 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D22档位客户数',
    D21 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D21档位客户数',
    D20 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D20档位客户数',
    D19 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D19档位客户数',
    D18 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D18档位客户数',
    D17 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D17档位客户数',
    D16 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D16档位客户数',
    D15 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D15档位客户数',
    D14 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D14档位客户数',
    D13 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D13档位客户数',
    D12 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D12档位客户数',
    D11 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D11档位客户数',
    D10 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D10档位客户数',
    D9 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D9档位客户数',
    D8 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D8档位客户数',
    D7 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D7档位客户数',
    D6 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D6档位客户数',
    D5 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D5档位客户数',
    D4 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D4档位客户数',
    D3 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D3档位客户数',
    D2 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D2档位客户数',
    D1 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'D1档位客户数',
    TOTAL DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总客户数',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID, YEAR, MONTH, WEEK_SEQ),
    UNIQUE KEY UK_YEAR_MONTH_WEEK_REGION (YEAR, MONTH, WEEK_SEQ, REGION),
    INDEX IDX_YEAR_MONTH_WEEK (YEAR, MONTH, WEEK_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
PARTITION BY RANGE (YEAR * 10000 + MONTH * 100 + WEEK_SEQ) (
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ============================================
-- 2. 创建 cigarette_distribution_info 分区表
-- ============================================
CREATE TABLE IF NOT EXISTS cigarette_distribution_info (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    YEAR INT NOT NULL COMMENT '年份',
    MONTH INT NOT NULL COMMENT '月份',
    WEEK_SEQ INT NOT NULL COMMENT '周序号',
    CIG_CODE VARCHAR(255) NOT NULL COMMENT '卷烟代码',
    CIG_NAME VARCHAR(255) NOT NULL COMMENT '卷烟名称',
    DELIVERY_METHOD VARCHAR(255) COMMENT '投放方法',
    DELIVERY_ETYPE VARCHAR(255) COMMENT '扩展投放类型',
    TAG VARCHAR(255) COMMENT '标签',
    ADV DECIMAL(18,2) COMMENT '预投放量',
    DELIVERY_AREA VARCHAR(255) COMMENT '投放区域',
    BZ VARCHAR(255) COMMENT '备注',
    HIGHEST_GRADE VARCHAR(255) COMMENT '最高档位',
    LOWEST_GRADE VARCHAR(255) COMMENT '最低档位',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID, YEAR, MONTH, WEEK_SEQ),
    INDEX IDX_CIG_CODE_NAME (CIG_CODE, CIG_NAME),
    INDEX IDX_YEAR_MONTH_WEEK (YEAR, MONTH, WEEK_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
PARTITION BY RANGE (YEAR * 10000 + MONTH * 100 + WEEK_SEQ) (
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ============================================
-- 3. 创建 cigarette_distribution_prediction 分区表
-- ============================================
CREATE TABLE IF NOT EXISTS cigarette_distribution_prediction (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    YEAR INT NOT NULL COMMENT '年份',
    MONTH INT NOT NULL COMMENT '月份',
    WEEK_SEQ INT NOT NULL COMMENT '周序号',
    CIG_CODE VARCHAR(255) NOT NULL COMMENT '卷烟代码',
    CIG_NAME VARCHAR(255) NOT NULL COMMENT '卷烟名称',
    DELIVERY_AREA VARCHAR(255) COMMENT '投放区域',
    DELIVERY_METHOD VARCHAR(255) COMMENT '投放方法',
    DELIVERY_ETYPE VARCHAR(255) COMMENT '扩展投放类型',
    D30 DECIMAL(18,2) COMMENT 'D30档位分配值',
    D29 DECIMAL(18,2) COMMENT 'D29档位分配值',
    D28 DECIMAL(18,2) COMMENT 'D28档位分配值',
    D27 DECIMAL(18,2) COMMENT 'D27档位分配值',
    D26 DECIMAL(18,2) COMMENT 'D26档位分配值',
    D25 DECIMAL(18,2) COMMENT 'D25档位分配值',
    D24 DECIMAL(18,2) COMMENT 'D24档位分配值',
    D23 DECIMAL(18,2) COMMENT 'D23档位分配值',
    D22 DECIMAL(18,2) COMMENT 'D22档位分配值',
    D21 DECIMAL(18,2) COMMENT 'D21档位分配值',
    D20 DECIMAL(18,2) COMMENT 'D20档位分配值',
    D19 DECIMAL(18,2) COMMENT 'D19档位分配值',
    D18 DECIMAL(18,2) COMMENT 'D18档位分配值',
    D17 DECIMAL(18,2) COMMENT 'D17档位分配值',
    D16 DECIMAL(18,2) COMMENT 'D16档位分配值',
    D15 DECIMAL(18,2) COMMENT 'D15档位分配值',
    D14 DECIMAL(18,2) COMMENT 'D14档位分配值',
    D13 DECIMAL(18,2) COMMENT 'D13档位分配值',
    D12 DECIMAL(18,2) COMMENT 'D12档位分配值',
    D11 DECIMAL(18,2) COMMENT 'D11档位分配值',
    D10 DECIMAL(18,2) COMMENT 'D10档位分配值',
    D9 DECIMAL(18,2) COMMENT 'D9档位分配值',
    D8 DECIMAL(18,2) COMMENT 'D8档位分配值',
    D7 DECIMAL(18,2) COMMENT 'D7档位分配值',
    D6 DECIMAL(18,2) COMMENT 'D6档位分配值',
    D5 DECIMAL(18,2) COMMENT 'D5档位分配值',
    D4 DECIMAL(18,2) COMMENT 'D4档位分配值',
    D3 DECIMAL(18,2) COMMENT 'D3档位分配值',
    D2 DECIMAL(18,2) COMMENT 'D2档位分配值',
    D1 DECIMAL(18,2) COMMENT 'D1档位分配值',
    ACTUAL_DELIVERY DECIMAL(18,2) COMMENT '实际投放量',
    DEPLOYINFO_CODE VARCHAR(255) COMMENT '投放信息编码',
    BZ VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID, YEAR, MONTH, WEEK_SEQ),
    INDEX IDX_CIG_CODE_NAME (CIG_CODE, CIG_NAME),
    INDEX IDX_YEAR_MONTH_WEEK (YEAR, MONTH, WEEK_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
PARTITION BY RANGE (YEAR * 10000 + MONTH * 100 + WEEK_SEQ) (
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ============================================
-- 4. 创建 base_cigarette_price 卷烟基础价位信息表
--    用途：查询卷烟批发价、价类/价档、高低价位
-- ============================================
CREATE TABLE IF NOT EXISTS base_cigarette_price (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    CIG_CODE VARCHAR(64) NOT NULL COMMENT '卷烟代码',
    CIG_BARCODE VARCHAR(64) COMMENT '卷烟编码/条码',
    CIG_NAME VARCHAR(255) NOT NULL COMMENT '卷烟名称',
    BRAND_NAME VARCHAR(255) COMMENT '品牌名称',
    MANUFACTURER VARCHAR(255) COMMENT '工业企业名称',
    WHOLESALE_PRICE DECIMAL(18,2) COMMENT '批发价',
    PRICE_CLASS VARCHAR(64) COMMENT '价类',
    PRICE_GRADE VARCHAR(64) COMMENT '价档',
    IS_HIGH_PRICE TINYINT(1) DEFAULT 0 COMMENT '高/低价位(1高0低)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CIG_CODE (CIG_CODE),
    INDEX IDX_CIG_NAME (CIG_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- 5. 创建按价位段自选投放预测分区表 cigarette_distribution_prediction_price
--    结构与现有 prediction 分区表保持一致，专用于价位段自选投放
-- ============================================
CREATE TABLE IF NOT EXISTS cigarette_distribution_prediction_price (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    YEAR INT NOT NULL COMMENT '年份',
    MONTH INT NOT NULL COMMENT '月份',
    WEEK_SEQ INT NOT NULL COMMENT '周序号',
    CIG_CODE VARCHAR(255) NOT NULL COMMENT '卷烟代码',
    CIG_NAME VARCHAR(255) NOT NULL COMMENT '卷烟名称',
    DELIVERY_AREA VARCHAR(255) COMMENT '投放区域',
    DELIVERY_METHOD VARCHAR(255) COMMENT '投放方法',
    DELIVERY_ETYPE VARCHAR(255) COMMENT '扩展投放类型',
    D30 DECIMAL(18,2) COMMENT 'D30档位分配值',
    D29 DECIMAL(18,2) COMMENT 'D29档位分配值',
    D28 DECIMAL(18,2) COMMENT 'D28档位分配值',
    D27 DECIMAL(18,2) COMMENT 'D27档位分配值',
    D26 DECIMAL(18,2) COMMENT 'D26档位分配值',
    D25 DECIMAL(18,2) COMMENT 'D25档位分配值',
    D24 DECIMAL(18,2) COMMENT 'D24档位分配值',
    D23 DECIMAL(18,2) COMMENT 'D23档位分配值',
    D22 DECIMAL(18,2) COMMENT 'D22档位分配值',
    D21 DECIMAL(18,2) COMMENT 'D21档位分配值',
    D20 DECIMAL(18,2) COMMENT 'D20档位分配值',
    D19 DECIMAL(18,2) COMMENT 'D19档位分配值',
    D18 DECIMAL(18,2) COMMENT 'D18档位分配值',
    D17 DECIMAL(18,2) COMMENT 'D17档位分配值',
    D16 DECIMAL(18,2) COMMENT 'D16档位分配值',
    D15 DECIMAL(18,2) COMMENT 'D15档位分配值',
    D14 DECIMAL(18,2) COMMENT 'D14档位分配值',
    D13 DECIMAL(18,2) COMMENT 'D13档位分配值',
    D12 DECIMAL(18,2) COMMENT 'D12档位分配值',
    D11 DECIMAL(18,2) COMMENT 'D11档位分配值',
    D10 DECIMAL(18,2) COMMENT 'D10档位分配值',
    D9 DECIMAL(18,2) COMMENT 'D9档位分配值',
    D8 DECIMAL(18,2) COMMENT 'D8档位分配值',
    D7 DECIMAL(18,2) COMMENT 'D7档位分配值',
    D6 DECIMAL(18,2) COMMENT 'D6档位分配值',
    D5 DECIMAL(18,2) COMMENT 'D5档位分配值',
    D4 DECIMAL(18,2) COMMENT 'D4档位分配值',
    D3 DECIMAL(18,2) COMMENT 'D3档位分配值',
    D2 DECIMAL(18,2) COMMENT 'D2档位分配值',
    D1 DECIMAL(18,2) COMMENT 'D1档位分配值',
    ACTUAL_DELIVERY DECIMAL(18,2) COMMENT '实际投放量',
    DEPLOYINFO_CODE VARCHAR(255) COMMENT '投放信息编码',
    BZ VARCHAR(255) COMMENT '备注',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID, YEAR, MONTH, WEEK_SEQ),
    INDEX IDX_CIG_CODE_NAME_P (CIG_CODE, CIG_NAME),
    INDEX IDX_YEAR_MONTH_WEEK_P (YEAR, MONTH, WEEK_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
PARTITION BY RANGE (YEAR * 10000 + MONTH * 100 + WEEK_SEQ) (
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ============================================
-- 验证表创建成功
-- ============================================
SELECT 
    TABLE_NAME,
    TABLE_TYPE,
    PARTITION_EXPRESSION,
    PARTITION_DESCRIPTION
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN (
      'region_customer_statistics',
      'cigarette_distribution_info',
      'cigarette_distribution_prediction',
      'cigarette_distribution_prediction_price',
      'base_cigarette_price'
  );

