-- ============================================
-- 创建 customer_filter 分区表
-- 用途：替代临时表 temp_customer_filter_*，按时间分区存储过滤后的客户数据
-- 分区策略：按 YEAR, MONTH, WEEK_SEQ 分区，自动清理超过一周的分区
-- ============================================

CREATE TABLE IF NOT EXISTS customer_filter (
    -- 分区键（必须包含在主键中）
    YEAR INT NOT NULL COMMENT '年份',
    MONTH INT NOT NULL COMMENT '月份',
    WEEK_SEQ INT NOT NULL COMMENT '周序号',
    
    -- 继承 base_customer_info 的所有字段（除了 ID，因为分区表需要复合主键）
    CUST_CODE VARCHAR(50) NOT NULL COMMENT '客户代码',
    CUST_ID VARCHAR(50) DEFAULT NULL COMMENT '客户ID',
    GRADE VARCHAR(20) DEFAULT NULL COMMENT '档位',
    ORDER_CYCLE VARCHAR(20) DEFAULT NULL COMMENT '订单周期',
    CREDIT_LEVEL VARCHAR(20) DEFAULT NULL COMMENT '信用等级',
    MARKET_TYPE VARCHAR(20) DEFAULT NULL COMMENT '市场类型',
    CLASSIFICATION_CODE VARCHAR(50) DEFAULT NULL COMMENT '分类代码',
    CUST_FORMAT VARCHAR(50) DEFAULT NULL COMMENT '客户格式',
    BUSINESS_DISTRICT_TYPE VARCHAR(50) DEFAULT NULL COMMENT '商圈类型',
    COMPANY_BRANCH VARCHAR(50) DEFAULT NULL COMMENT '分公司',
    COMPANY_DISTRICT VARCHAR(50) DEFAULT NULL COMMENT '公司区域',
    MARKET_DEPARTMENT VARCHAR(50) DEFAULT NULL COMMENT '市场部门',
    BUSINESS_STATUS VARCHAR(20) DEFAULT NULL COMMENT '经营状态',
    IS_MUTUAL_AID_GROUP VARCHAR(20) DEFAULT NULL COMMENT '是否互助小组',
    GROUP_NAME VARCHAR(100) DEFAULT NULL COMMENT '小组名称',
    QUALITY_DATA_SHARE VARCHAR(20) DEFAULT NULL COMMENT '优质数据共享客户',
    DYNAMIC_TAGS JSON DEFAULT NULL COMMENT '动态标签（JSON格式，从base_customer_info同步）',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 复合主键：CUST_CODE + 分区键
    PRIMARY KEY (CUST_CODE, YEAR, MONTH, WEEK_SEQ),
    -- 索引：分区键索引（用于分区裁剪）
    INDEX IDX_YEAR_MONTH_WEEK (YEAR, MONTH, WEEK_SEQ),
    -- 索引：常用查询字段
    INDEX IDX_REGION (COMPANY_DISTRICT),
    INDEX IDX_GRADE (GRADE),
    INDEX IDX_ORDER_CYCLE (ORDER_CYCLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC
PARTITION BY RANGE (YEAR * 10000 + MONTH * 100 + WEEK_SEQ) (
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ============================================
-- 验证表创建成功
-- ============================================
SELECT 
    TABLE_NAME,
    TABLE_TYPE,
    PARTITION_EXPRESSION,
    PARTITION_DESCRIPTION
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'customer_filter';

